export const SEO_CONFIG = {
  home: {
    title: "Diseño web e inteligencia artificial para negocios",
    description: "Creamos sitios web y tarjetas digitales a medida, chatbots con IA y herramientas para atraer, atender y convertir clientes. Soluciones para empresas en Colombia.",
    keywords: "desarrollo software a medida, soluciones inteligencia artificial, automatización empresarial Colombia, chatbots IA, ecosistemas digitales",
    path: "/",
    ogImage: "/og/og-home.jpg",
  },
  quienesSomos: {
    title: "Quiénes Somos - Estudio de Ingeniería Digital",
    description: "Conoce nuestro estudio de ingeniería digital y arquitectura tecnológica. Investigación continua, herramientas de vanguardia y verdadero interés en tus usuarios.",
    keywords: "quiénes somos, agencia software Colombia, estudio ingeniería digital, equipo desarrollo IA",
    path: "/quienes-somos.html",
    ogImage: "/og/og-default.jpg",
  },
  ecosistema: {
    title: "Ecosistema - Pipeline Digital Completo",
    description: "Conoce cómo una estrategia conecta presencia digital, atención con IA y seguimiento para guiar a las personas desde el primer contacto hasta la consulta.",
    keywords: "ecosistema digital, pipeline ventas, herramientas automatización conectadas, sistema conversión clientes",
    path: "/ecosistema.html",
    ogImage: "/og/og-ecosistema.jpg",
  },
  blog: {
    title: "Blog y Novedades",
    description: "Guías y artículos prácticos sobre ventas, sitios web, inteligencia artificial y marketing digital para negocios.",
    keywords: "blog marketing digital, artículos IA, automatización WhatsApp, marketing B2B Colombia",
    path: "/blog.html",
    ogImage: "/og/og-default.jpg",
  },
  chatbot: {
    title: "BotWeb IA - Chatbot Inteligente para Atención Automatizada",
    description: "Atiende a tus clientes 24/7 con nuestro Chatbot Inteligente. Integrado con WhatsApp y web, nuestro asistente virtual IA cualifica leads y cierra ventas automáticamente.",
    keywords: "chatbot inteligente, asistente virtual IA, bot conversacional, atención automatizada 24/7, chatbot WhatsApp, IA conversacional",
    path: "/chatbot.html",
    ogImage: "/og/og-chatbot.jpg",
  },
  canal1: {
    title: "Canal1 Chatbot - Multiagente Inteligente para WhatsApp",
    description: "Sistema multiagente que atiende, califica y distribuye leads a tu equipo de asesores en WhatsApp. Un solo número, múltiples agentes.",
    keywords: "chatbot multiagente, distribución leads WhatsApp, chatbot equipo ventas, canal1 WhatsApp",
    path: "/canal1-chatbot.html",
    ogImage: "/og/og-chatbot.jpg",
  },
  guardian: {
    title: "Guardián de Difusión - Automatización Masiva en WhatsApp",
    description: "Envío masivo seguro y calentamiento de cuentas de WhatsApp. Nuestra herramienta protege tus líneas mientras automatizas la difusión comercial.",
    keywords: "automatización WhatsApp, difusión masiva WhatsApp, envío masivo seguro, calentamiento cuentas WhatsApp, marketing WhatsApp",
    path: "/guardian-difusion.html",
    robots: "noindex, follow",
    ogImage: "/og/og-guardian.jpg",
  },
  calentador: {
    title: "Calentador de WhatsApp - Calentamiento Automático de Cuentas",
    description: "App de calentamiento automático de cuentas WhatsApp. Evita bloqueos, construye reputación y escala tus campañas de mensajería.",
    keywords: "calentador WhatsApp, calentar cuentas WhatsApp, evitar bloqueo WhatsApp, reputación cuenta WhatsApp",
    path: "/calentador-cuentas.html",
    robots: "noindex, follow",
    ogImage: "/og/og-guardian.jpg",
  },
  extractor: {
    title: "Extractor PLUS - Minería de Grupos y Contactos WhatsApp",
    description: "Extrae contactos y grupos de WhatsApp de forma segura y automatizada. Extractor PLUS se conecta a WhatsApp Web para minería de datos ética y sin baneos.",
    keywords: "extractor grupos whatsapp, extractor contactos whatsapp, minería de datos whatsapp, extraer miembros grupos, software extracción whatsapp",
    path: "/extractor.html",
    robots: "noindex, follow",
    ogImage: "/og/og-extractor.jpg",
  },
  fanpage: {
    title: "Fanpage Envío Masivo - Facebook e Instagram",
    description: "Plataforma de envío masivo para Facebook e Instagram. Automatiza tus campañas y llega a más clientes potenciales.",
    keywords: "envío masivo Facebook, automatización Instagram, fanpage marketing, difusión masiva redes sociales",
    path: "/fanpage-envio-masivo.html",
    ogImage: "/og/og-default.jpg",
  },
  autopublisher: {
    title: "Publicación organizada en grupos de Facebook",
    description: "Prepara y organiza publicaciones para grupos de Facebook relevantes para tu negocio. Conoce AutoPublisher Pro y su flujo de publicación asistida.",
    keywords: "publicar en grupos de Facebook, gestión de publicaciones, marketing en Facebook para negocios",
    path: "/autopublisher.html",
    ogImage: "/og/og-default.jpg",
  },
  auditor: {
    title: "Auditor Estratégico IA - Análisis SEO y Conversión",
    description: "Realiza una auditoría web inteligente impulsada por IA. Evalúa el estado SEO y UX/UI de tu sitio, recibiendo recomendaciones clave para mejorar la conversión.",
    keywords: "auditoría SEO, análisis presencia digital, auditor web IA, evaluación sitio web, optimización conversión, análisis experiencia usuario",
    path: "/auditor-estrategico.html",
    ogImage: "/og/og-auditor.jpg",
  },
  auditorSitio: {
    title: "Auditor de Sitio Web con IA",
    description: "Análisis profesional de tu sitio web con IA. Obtén recomendaciones específicas sobre diseño, UX, conversión y performance.",
    keywords: "auditor sitio web, análisis web IA, auditoría UX, recomendaciones diseño web, performance web",
    path: "/auditor-sitio-web.html",
    ogImage: "/og/og-auditor.jpg",
  },
  tarjeta: {
    title: "Tarjeta digital profesional para negocios",
    description: "Presenta tu negocio en una tarjeta digital personalizada con tus servicios, datos de contacto, ubicación y enlaces directos para facilitar consultas.",
    keywords: "tarjeta digital para negocios, tarjeta profesional digital, perfil digital para empresas, tarjeta de contacto digital",
    path: "/tarjeta-digital.html",
    ogImage: "/og/og-tarjeta.jpg",
  },
  solucionesDigitales: {
    title: "Planes de tarjetas digitales para negocios",
    description: "Compara tres modelos de tarjeta digital profesional. Elige el nivel que se ajusta a tu negocio y presenta tus servicios con diseño personalizado.",
    keywords: "tarjeta digital negocios, tarjeta VIP digital, identidad corporativa digital, tarjeta pago único",
    path: "/solucionesdigitales.html",
    ogImage: "/og/og-tarjeta.jpg",
  },
  web: {
    title: "Desarrollo Web UX/UI y Sitios a Medida",
    description: "Creación de ecosistemas digitales y desarrollo web con enfoque en UX/UI, optimizados para conversión y rendimiento empresarial.",
    keywords: "desarrollo web a medida, sitios web personalizados, desarrollo React, aplicaciones web modernas, diseño UX/UI, desarrollo frontend backend",
    path: "/sitios-web.html",
    ogImage: "/og/og-sitios-web.jpg",
  },
  probador: {
    title: "Probador Virtual IA - Prueba Productos con Inteligencia Artificial",
    description: "Prueba virtual de productos con Inteligencia Artificial. Visualiza cómo se ven antes de comprar.",
    keywords: "probador virtual IA, prueba virtual productos, realidad aumentada e-commerce, visualización productos IA",
    path: "/probador-virtual.html",
    ogImage: "/og/og-default.jpg",
  },
  tienda: {
    title: "Tienda - Catálogo de Soluciones Digitales",
    description: "Explora el catálogo de productos y servicios digitales de Soluciones Digitales IA Studio y encuentra la herramienta adecuada para tu negocio.",
    keywords: "tienda software, comprar chatbot, comprar automatización WhatsApp, catálogo soluciones digitales",
    path: "/tienda.html",
    ogImage: "/og/og-tienda.jpg",
  },
  producto: {
    title: "Producto - Detalles y Especificaciones",
    description: "Detalles del producto y especificaciones técnicas. Software y soluciones digitales con Inteligencia Artificial.",
    keywords: "producto software, especificaciones técnicas, software IA Colombia, detalle producto digital",
    path: "/producto.html",
    ogImage: "/og/og-tienda.jpg",
  },
  tutorialBotweb: {
    title: "Cómo Crear un Asistente con BotWeb IA - Tutorial",
    description: "Aprende paso a paso a configurar tu propio asistente de WhatsApp con inteligencia artificial. Responde clientes 24/7, captura leads y deriva a tu equipo.",
    keywords: "tutorial BotWeb, configurar chatbot WhatsApp, tutorial asistente IA, crear bot WhatsApp",
    path: "/tutorial-botweb.html",
    ogImage: "/og/og-chatbot.jpg",
  },
  tutorialGuardian: {
    title: "Tutorial Guardián de Difusión - Instalación Paso a Paso",
    description: "Aprende cómo descargar e instalar Guardián de Difusión. Protege tus envíos masivos de WhatsApp con nuestra arquitectura anti-baneo.",
    keywords: "tutorial guardián difusión, instalar difusión WhatsApp, manual envío masivo, configurar guardian",
    path: "/tutorial-guardian-difusion.html",
    robots: "noindex, follow",
    ogImage: "/og/og-guardian.jpg",
  },
  tutorialExtractor: {
    title: "Tutorial de Instalación - Extractor PLUS",
    description: "Manual de instalación y activación del Extractor PLUS de WhatsApp.",
    keywords: "tutorial extractor PLUS, instalar extractor WhatsApp, manual minería WhatsApp",
    path: "/tutorial-extractor.html",
    robots: "noindex, follow",
    ogImage: "/og/og-extractor.jpg",
  },
  tutorialCalentador: {
    title: "Calentador de Cuentas - Manual de Instalación",
    description: "Aprende paso a paso a instalar y activar el Calentador de Cuentas de WhatsApp. Descarga la demo, solicita tu token y calienta tus cuentas sin riesgo de bloqueo.",
    keywords: "tutorial calentador cuentas, instalar warmer WhatsApp, manual calentamiento cuentas",
    path: "/tutorial-calentador.html",
    robots: "noindex, follow",
    ogImage: "/og/og-guardian.jpg",
  },
  tutorialIA: {
    title: "Cómo Crear Contenido con IA - Tutorial Higgsfield AI",
    description: "Aprende paso a paso a crear contenido impactante con inteligencia artificial usando Higgsfield AI: videos, imágenes y campañas completas.",
    keywords: "tutorial IA contenido, Higgsfield AI tutorial, crear videos IA, imágenes inteligencia artificial",
    path: "/tutorial-ia.html",
    ogImage: "/og/og-default.jpg",
  },
  privacidad: {
    title: "Política de Privacidad",
    description: "Política de Privacidad y Tratamiento de Datos Personales de Soluciones Digitales IA. Ley 1581 de 2012 Colombia.",
    keywords: "política privacidad, tratamiento datos personales, ley 1581, habeas data",
    path: "/politica-privacidad.html",
    ogImage: "/og/og-default.jpg",
  }
};
